"""initial models

Revision ID: 17892ab566d1
Revises:
Create Date: 2024-06-25 23:10:27.366511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17892ab566d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_thread",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column(
            "time_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", name="messagerole"), nullable=False
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("parent_message_id", sa.Integer(), nullable=True),
        sa.Column("chat_thread_id", sa.Integer(), nullable=False),
        sa.Column("related_queries", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("image_results", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_thread_id"],
            ["chat_thread.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["chat_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("chat_message_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_message_id"],
            ["chat_message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_result")
    op.drop_table("chat_message")
    op.drop_table("chat_thread")
    # ### end Alembic commands ###
