"""Initial migration

Revision ID: 794c492ea0c2
Revises:
Create Date: 2024-06-25 22:32:02.026741

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "794c492ea0c2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
