"""agent response

Revision ID: 91d5d7402c69
Revises: 17892ab566d1
Create Date: 2024-06-28 22:33:33.540403

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91d5d7402c69"
down_revision: Union[str, None] = "17892ab566d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_message",
        sa.Column("agent_search_full_response", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message", "agent_search_full_response")
    # ### end Alembic commands ###
