# https://github.com/cohere-ai/cohere-toolkit/blob/main/.github/workflows/build_and_push_docker.yml

name: Create and publish container images

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  backend:
    permissions:
      contents: read
      packages: write
    uses: schmoaaaaah/farfalle/.github/workflows/build-container.yml@main
    with:
      container: backend
      version: ${{ github.event.release.tag_name }}
  frontend:
    permissions:
      contents: read
      packages: write
    uses: schmoaaaaah/farfalle/.github/workflows/build-container.yml@main
    with:
      container: frontend
      version: ${{ github.event.release.tag_name }}